#!/usr/bin/env bash
# FoundryX Issue Filing Script — generated by parallel-issue-discovery workflow
#
# REPO: anchapin/foundry-x | BASE: develop
# 9 issues prepared (3 ready-to-file + 6 revised). Scores 70-92.
#
# USAGE:
#   Review each issue body in .agents/issues-staging/*.md
#   Then run:  bash .agents/issues-staging/file-issues.sh
#   Or file individually by uncommenting sections below.
#
# All issues are DRAFTS for human triage. Edit titles/labels/bodies as needed.
set -euo pipefail
REPO="anchapin/foundry-x"
DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== Filing 9 issues to $REPO ==="
echo ""

# ─── 1. benchmarks-01 (score 92, P2) ──────────────────────────────────────
gh issue create --repo "$REPO" \
  --title "feat(benchmarks): assert pruning preserves tool_result and user_prompt events" \
  --body-file "$DIR/01-benchmarks-prune-preserve.md" \
  --label "agent-proposed,area-benchmarks,kpi-regression-rate,phase-2,size-m"
echo "  -> filed benchmarks-01"

# ─── 2. infra-01 (score 91, P2) ───────────────────────────────────────────
gh issue create --repo "$REPO" \
  --title "test(infra): guard Python version drift between Dockerfile and CI" \
  --body-file "$DIR/02-infra-python-version-drift.md" \
  --label "agent-proposed,area-infra,kpi-regression-rate,phase-1,size-s"
echo "  -> filed infra-01"

# ─── 3. execution-01 (score 88, P2) ───────────────────────────────────────
gh issue create --repo "$REPO" \
  --title "fix(execution): classify empty model response as failure not success" \
  --body-file "$DIR/03-execution-empty-response.md" \
  --label "agent-proposed,area-execution,kpi-regression-rate,phase-1,size-s"
echo "  -> filed execution-01"

# ─── 4. trace-01 (score 78, P2) ───────────────────────────────────────────
gh issue create --repo "$REPO" \
  --title "fix(trace): skip corrupted JSONL lines in read-path methods" \
  --body-file "$DIR/04-trace-jsonl-corruption.md" \
  --label "agent-proposed,area-trace,kpi-cycle-time,phase-1,size-s"
echo "  -> filed trace-01"

# ─── 5. observability-01 (score 77, P2) ───────────────────────────────────
gh issue create --repo "$REPO" \
  --title "fix(observability): retain auxiliary KPI signals in history log trend" \
  --body-file "$DIR/05-observability-kpi-history.md" \
  --label "agent-proposed,area-observability,kpi-cycle-time,phase-3,size-s"
echo "  -> filed observability-01"

# ─── 6. docs-01 (score 76, P3) ────────────────────────────────────────────
gh issue create --repo "$REPO" \
  --title "fix(docs): correct stale digester constant line citations in CONTEXT.md" \
  --body-file "$DIR/06-docs-context-citations.md" \
  --label "agent-proposed,area-docs,kpi-cycle-time,phase-3,size-s"
echo "  -> filed docs-01"

# ─── 7. security-02 (score 75, P0) ────────────────────────────────────────
gh issue create --repo "$REPO" \
  --title "fix(security): confine bash skill cwd to workspace root" \
  --body-file "$DIR/07-security-bash-cwd.md" \
  --label "agent-proposed,area-security,kpi-regression-rate,phase-1,size-s"
echo "  -> filed security-02"

# ─── 8. security-01 (score 72, P0) ────────────────────────────────────────
gh issue create --repo "$REPO" \
  --title "test(security): add drift guard for injection firewall pattern parity" \
  --body-file "$DIR/08-security-injection-drift.md" \
  --label "agent-proposed,area-security,kpi-regression-rate,phase-3,size-s"
echo "  -> filed security-01"

# ─── 9. evolution-01 (score 70, P2) ───────────────────────────────────────
gh issue create --repo "$REPO" \
  --title "fix(critic): enforce gate_timeout_s on quantization-sweep subprocess" \
  --body-file "$DIR/09-evolution-sweep-timeout.md" \
  --label "agent-proposed,area-evolution,kpi-regression-rate,phase-3,size-s"
echo "  -> filed evolution-01"

echo ""
echo "=== All 9 issues filed ==="
